import assert from "node:assert/strict";
import { test } from "node:test";
import {
  highestSlot,
  closures,
  builtNames,
  bytecodeLength,
  inlinedInto,
  clientLibraries,
  ratchet,
  hotFunctions,
  rebaselineEngine,
} from "./fast-code-parsers.mjs";

const header = (name, size) =>
  `[generated bytecode for function: ${name} (0x123 <SharedFunctionInfo ${name}>)]\nBytecode length: ${size}\n`;
const inline =
  "Inlining 0x1 {0x2 <SharedFunctionInfo C>} into 0x3 {0x4 <SharedFunctionInfo run>} (inside try-block)";

await test("module slots count captured names but omit cells and shadowed names", () => {
  const code =
    'import { remote } from "pkg"; const local = 1; const shadow = 2; export const cell = 3; function read(shadow) { return local + cell + shadow + remote }';
  assert.equal(highestSlot(code), 3);
  assert.equal(highestSlot("export const x = 1;"), 2);
});

await test("hot functions count their closures, defaults, and constructor fields", () => {
  const code =
    "function run(defaultFn = () => 0) { const next = () => () => 1; function local() {} return next; } class C { fn = () => 1; static shared = () => 2; constructor() { const local = function() {}; } }";
  assert.deepEqual(closures(code, ["run", "C"]), { run: 3, C: 2 });
  assert.throws(() => closures(code, ["missing"]), /Missing hot function/);
});

await test("source maps find renamed functions and class expressions across lines", () => {
  const code = "function a() {}\nvar b = class {};";
  const map = {
    sources: ["../src/index.ts"],
    sourcesContent: ["function run() {}\nclass C {}"],
    mappings: "AAAA;AACA",
  };
  assert.deepEqual(builtNames(code, map, ["run", "C"]), { run: "a", C: "b" });
});

await test("bytecode uses the named function and fails closed on missing or mixed lengths", () => {
  assert.equal(bytecodeLength(header("other", 999) + header("hot", 451), "hot"), 451);
  assert.throws(() => bytecodeLength(header("other", 1), "hot"), /Missing or ambiguous/);
  assert.throws(() => bytecodeLength(header("hot", 1) + header("hot", 2), "hot"), /ambiguous/);
});

await test("inlining requires a completed edge into the named root", () => {
  assert.equal(inlinedInto(inline, "C", "run"), true);
  assert.equal(
    inlinedInto("Considering 0x1 {0x2 <SharedFunctionInfo C>} for inlining", "C", "run"),
    false,
  );
  assert.equal(inlinedInto(inline, "C", "other"), false);
});

await test("client maps name all three libraries and omit sources with no mappings", () => {
  const map = {
    sources: [
      "../../node_modules/.pnpm/zod@4/node_modules/zod/v4/core.js",
      "../../node_modules/drizzle-orm/index.js",
      "../../node_modules/@electric-sql/pglite/dist/index.js",
      "../../node_modules/zodish/index.js",
    ],
    mappings: "AAAA,ACAA,ACAA,ACAA",
  };
  assert.deepEqual(clientLibraries(map), ["zod", "drizzle", "pglite"]);
  assert.deepEqual(clientLibraries({ ...map, mappings: "AGAA" }), []);
});

await test("ratchets allow a lower value and reject a rise or missing baseline", () => {
  ratchet("hot", 450, 451);
  ratchet("hot", 451, 451);
  assert.throws(() => ratchet("hot", 452, 451), /452 > baseline 451/);
  assert.throws(() => ratchet("hot", 1, undefined), /baseline undefined/);
});

const oldEngineBaseline = {
  node: "v0.fixture",
  v8: "fixture-v8",
  bytecode: Object.fromEntries(hotFunctions.map((name) => [name, name === "runOnce" ? 502 : 100])),
  slots: { core: 341, react: 25 },
  closures: { runOnce: 0 },
  client: { zod: 0, drizzle: 0, pglite: 0 },
  inlining: { OperationCtxIntoRunOnce: true },
};
const newEngine = { node: "v24.fixture", v8: "new-fixture-v8" };

await test("an engine rebaseline changes only engine fields and bytecode numbers", () => {
  const bytecode = { ...oldEngineBaseline.bytecode, settleRun: 120, OperationCtx: 90 };
  const next = rebaselineEngine(oldEngineBaseline, newEngine, bytecode, true);
  assert.deepEqual(next, { ...oldEngineBaseline, ...newEngine, bytecode });
  assert.equal(oldEngineBaseline.node, "v0.fixture");
});

await test("an engine rebaseline rejects bytecode growth above 460 and keeps the inline promise", () => {
  const bytecode = oldEngineBaseline.bytecode;
  assert.throws(
    () => rebaselineEngine(oldEngineBaseline, newEngine, { ...bytecode, settleRun: 461 }, true),
    /cannot raise bytecode above 460/,
  );
  assert.throws(
    () => rebaselineEngine(oldEngineBaseline, newEngine, { ...bytecode, runOnce: 503 }, true),
    /cannot raise bytecode above 460/,
  );
  assert.throws(
    () => rebaselineEngine(oldEngineBaseline, newEngine, bytecode, false),
    /must remain inlined/,
  );
  assert.throws(
    () =>
      rebaselineEngine(
        { ...oldEngineBaseline, inlining: { OperationCtxIntoRunOnce: false } },
        newEngine,
        bytecode,
        true,
      ),
    /must remain inlined/,
  );
});
